### ISSUE TITLE
[QUESTION] .net core

### ISSUE THREAD

**Issue by wowsuchdeveloper** [ailen0ada/xxHash4net#1]
Will this work with .net core ?

**Comment by ailen0ada** [comment]
Currently not available -- only net4, but I'll implement it soon.

**Comment by wowsuchdeveloper** [comment]
When I try to install the package I get this:
log  : Installing xxHash4net 1.1.1.
error: Access to the path 'C:\Users*.nuget\packages\xxHash4net\1.1.1' is denied.
log  : Installing xxHash4net 1.1.1.

**Comment by vector-man** [comment]
I'm also getting the same error as wowsuchdeveloper. I created an issue with the full output of the error I got.
